name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ تنزيل ملفات المشروع
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ تثبيت المتطلبات
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk unzip zip git
          pip install --upgrade pip
          pip install buildozer cython

      # 3️⃣ تهيئة Buildozer
      - name: Init buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      # 4️⃣ بناء APK
      - name: Build APK
        run: |
          buildozer android debug

      # 5️⃣ رفع ملف APK في الـ Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ExpenseApp-APK
          path: bin/*.apk
